/*26)  FAÇA  UM  ALGORITMO  PARA  LER:  QUANTIDADE  ATUAL  EM  ESTOQUE, 
QUANTIDADE  MÁXIMA  EM  ESTOQUE  E QUANTIDADE  MÍNIMA  EM  ESTOQUE  
DE  UM  PRODUTO.  CALCULAR  E  ESCREVER  A  QUANTIDADE  MÉDIA  
((QUANTIDADE MÉDIA = QUANTIDADE MÁXIMA + QUANTIDADE MÍNIMA)/2). 
SE A QUANTIDADE EM ESTOQUE FOR MAIOR OU IGUAL A  QUANTIDADE  MÉDIA 
ESCREVER  A  MENSAGEM  'NÃO  EFETUAR  COMPRA',  SENÃO  ESCREVER  A 
MENSAGEM  'EFETUAR COMPRA'. 
*/

package exerciciosFaccat;

public class Exercicio26Faccat {

	public static void main(String[] args) {
		// TODO Auto-generated method stub

	}

}
