/*25) FAÇA UM  ALGORITMO PARA LER: NÚMERO DA  CONTA DO CLIENTE, SALDO, 
DÉBITO E  CRÉDITO. APÓS,  CALCULAR E ESCREVER O SALDO ATUAL 
(SALDO ATUAL = SALDO - DÉBITO + CRÉDITO). TAMBÉM TESTAR SE SALDO
ATUAL FOR MAIOR OU IGUAL A ZERO ESCREVER A MENSAGEM 'SALDO POSITIVO', 
SENÃO ESCREVER A MENSAGEM 'SALDO NEGATIVO'. */


package exerciciosFaccat;

public class Exercicio25Faccat {

	public static void main(String[] args) {

	}

}
