/*24) LER O SALÁRIO FIXO E O VALOR DAS VENDAS EFETUADAS PELO VENDEDOR DE 
UMA EMPRESA. SABENDO-SE QUE ELE  RECEBE  UMA  COMISSÃO  DE  3%  SOBRE 
O  TOTAL  DAS  VENDAS  ATÉ  R$  1.500,00  MAIS  5%  SOBRE  O  QUE ULTRAPASSAR
ESTE VALOR, CALCULAR E ESCREVER O SEU SALÁRIO TOTAL. */

package exerciciosFaccat;

public class Exercicio24Faccat {

}
